detect_relations: true

FkLiederbuchLied:
  connection: doctrine
  tableName: fkLiederbuchLied
  columns:
    id:
      type: integer(8)
      notnull: false
      primary: true
      autoincrement: true
    liederbuch_id:
      type: integer(8)
      notnull: false
      primary: false
      autoincrement: false
    lied_id:
      type: integer(8)
      notnull: false
      primary: false
      autoincrement: false
    liednr:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
Lied:
  actAs: { Timestampable: ~ }
  connection: doctrine
  tableName: Lied
  columns:
    id:
      type: integer(8)
      notnull: false
      primary: true
      autoincrement: true
    titel:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
    rubrik_id:
      type: integer(8)
      notnull: false
      primary: false
      autoincrement: false
    stichwoerter:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
    bemerkungen:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
  relations:
    Liederbucher:
      foreignAlias: Lieder
      class: Liederbuch
      refClass: FkLiederbuchLied
      onUpdate: CASCADE
      onDelete: NO ACTION
    Rubrik:
      foreignAlias: Rubriken
      class: Rubrik
      onUpdate: CASCADE
      onDelete: NO ACTION
    Liedtext:
      type: many
      class: Liedtext
      local: id
      foreign: lied_id
      cascade: [delete]
    Refrain:
      type: many
      class: Refrain
      local: id
      foreign: lied_id
      cascade: [delete]
Liederbuch:
  connection: doctrine
  tableName: Liederbuch
  columns:
    id:
      type: integer(8)
      primary: true
      autoincrement: true
    buchname:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
    beschreibung:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
Liedtext:
  connection: doctrine
  tableName: Liedtext
  columns:
    id:
      type: integer(8)
      notnull: false
      primary: true
      autoincrement: true
    lied_id:
      type: integer(8)
      notnull: false
      primary: false
      autoincrement: false
    ueberschrift:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
    ueberschrifttyp:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
    strophe:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
    refrain_id:
      type: integer(8)
      notnull: false
      primary: false
      autoincrement: false
    reihenfolge:
      type: integer(8)
      notnull: false
      primary: false
      autoincrement: false
  relations:
    Lied:
      class: Lied
      onUpdate: CASCADE
      onDelete: CASCADE
    Refrain:
      foreignAlias: Strophen
      class: Refrain
      onUpdate: CASCADE
      onDelete: NO ACTION
Refrain:
  connection: doctrine
  tableName: Refrain
  columns:
    id:
      type: integer(8)
      notnull: false
      primary: true
      autoincrement: true
    refrainnr:
      type: integer(8)
      notnull: false
      primary: false
      autoincrement: false
    refrain:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
    lied_id:
      type: integer(8)
      notnull: false
      primary: false
      autoincrement: false
Rubrik:
  connection: doctrine
  tableName: Rubrik
  columns:
    id:
      type: integer(8)
      notnull: false
      primary: true
      autoincrement: true
    rubrik:
      type: text()
      notnull: false
      primary: false
      autoincrement: false
    reihenfolge:
      type: integer(8)
      notnull: false
      primary: false
      autoincrement: false
