# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }
  
lied_default:
  url:   /lied
  param: { module: lied, sf_format: json }

lied:
  url:   /lied/:action/*
  param: { module: lied, sf_format: json }

strophe_default:
  url:   /strophe
  param: { module: strophe, sf_format: json }

strophe:
  url:   /strophe/:action/*
  param: { module: strophe, sf_format: json }

refrain_default:
  url:   /refrain
  param: { module: refrain, sf_format: json }

refrain:
  url:   /refrain/:action/*
  param: { module: refrain, sf_format: json }

liederbuch:
  url:   /liederbuch/*
  param: { module: liederbuch, sf_format: json }

rubrik:
  url:   /rubrik/*
  param: { module: rubrik, sf_format: json }

versioncontrol_default:
  url:   /versioncontrol
  param: { module: versioncontrol, sf_format: json }

versioncontrol_plain:
  url:   /versioncontrol/plain
  param: { module: versioncontrol, action: plain }

versioncontrol:
  url:   /versioncontrol/:action/*
  param: { module: versioncontrol, sf_format: json }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*