<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Liederbuch', 'doctrine');

/**
 * BaseLiederbuch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $buchname
 * @property text $beschreibung
 * @property Doctrine_Collection $FkLiederbuchLied
 * @property Doctrine_Collection $Lieder
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method text                getBuchname()         Returns the current record's "buchname" value
 * @method text                getBeschreibung()     Returns the current record's "beschreibung" value
 * @method Doctrine_Collection getFkLiederbuchLied() Returns the current record's "FkLiederbuchLied" collection
 * @method Doctrine_Collection getLieder()           Returns the current record's "Lieder" collection
 * @method Liederbuch          setId()               Sets the current record's "id" value
 * @method Liederbuch          setBuchname()         Sets the current record's "buchname" value
 * @method Liederbuch          setBeschreibung()     Sets the current record's "beschreibung" value
 * @method Liederbuch          setFkLiederbuchLied() Sets the current record's "FkLiederbuchLied" collection
 * @method Liederbuch          setLieder()           Sets the current record's "Lieder" collection
 * 
 * @package    adonai
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLiederbuch extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Liederbuch');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('buchname', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('beschreibung', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FkLiederbuchLied', array(
             'local' => 'id',
             'foreign' => 'liederbuch_id'));

        $this->hasMany('Lied as Lieder', array(
             'refClass' => 'FkLiederbuchLied',
             'local' => 'liederbuch_id',
             'foreign' => 'lied_id'));
    }
}