<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FkLiederbuchLied', 'doctrine');

/**
 * BaseFkLiederbuchLied
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $liederbuch_id
 * @property integer $lied_id
 * @property text $liednr
 * @property Liederbuch $Liederbuch
 * @property Lied $Lied
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method integer          getLiederbuchId()  Returns the current record's "liederbuch_id" value
 * @method integer          getLiedId()        Returns the current record's "lied_id" value
 * @method text             getLiednr()        Returns the current record's "liednr" value
 * @method Liederbuch       getLiederbuch()    Returns the current record's "Liederbuch" value
 * @method Lied             getLied()          Returns the current record's "Lied" value
 * @method FkLiederbuchLied setId()            Sets the current record's "id" value
 * @method FkLiederbuchLied setLiederbuchId()  Sets the current record's "liederbuch_id" value
 * @method FkLiederbuchLied setLiedId()        Sets the current record's "lied_id" value
 * @method FkLiederbuchLied setLiednr()        Sets the current record's "liednr" value
 * @method FkLiederbuchLied setLiederbuch()    Sets the current record's "Liederbuch" value
 * @method FkLiederbuchLied setLied()          Sets the current record's "Lied" value
 * 
 * @package    adonai
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFkLiederbuchLied extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fkLiederbuchLied');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('liederbuch_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('lied_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('liednr', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Liederbuch', array(
             'local' => 'liederbuch_id',
             'foreign' => 'id'));

        $this->hasOne('Lied', array(
             'local' => 'lied_id',
             'foreign' => 'id'));
    }
}