<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Rubrik', 'doctrine');

/**
 * BaseRubrik
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $rubrik
 * @property integer $reihenfolge
 * @property Doctrine_Collection $Rubriken
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method text                getRubrik()      Returns the current record's "rubrik" value
 * @method integer             getReihenfolge() Returns the current record's "reihenfolge" value
 * @method Doctrine_Collection getRubriken()    Returns the current record's "Rubriken" collection
 * @method Rubrik              setId()          Sets the current record's "id" value
 * @method Rubrik              setRubrik()      Sets the current record's "rubrik" value
 * @method Rubrik              setReihenfolge() Sets the current record's "reihenfolge" value
 * @method Rubrik              setRubriken()    Sets the current record's "Rubriken" collection
 * 
 * @package    adonai
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRubrik extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Rubrik');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('rubrik', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('reihenfolge', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Lied as Rubriken', array(
             'local' => 'id',
             'foreign' => 'rubrik_id'));
    }
}