<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Refrain', 'doctrine');

/**
 * BaseRefrain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $refrainnr
 * @property text $refrain
 * @property integer $lied_id
 * @property Lied $Lied
 * @property Doctrine_Collection $Strophen
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method integer             getRefrainnr() Returns the current record's "refrainnr" value
 * @method text                getRefrain()   Returns the current record's "refrain" value
 * @method integer             getLiedId()    Returns the current record's "lied_id" value
 * @method Lied                getLied()      Returns the current record's "Lied" value
 * @method Doctrine_Collection getStrophen()  Returns the current record's "Strophen" collection
 * @method Refrain             setId()        Sets the current record's "id" value
 * @method Refrain             setRefrainnr() Sets the current record's "refrainnr" value
 * @method Refrain             setRefrain()   Sets the current record's "refrain" value
 * @method Refrain             setLiedId()    Sets the current record's "lied_id" value
 * @method Refrain             setLied()      Sets the current record's "Lied" value
 * @method Refrain             setStrophen()  Sets the current record's "Strophen" collection
 * 
 * @package    adonai
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRefrain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Refrain');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('refrainnr', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('refrain', 'text', null, array(
             'type' => 'text',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('lied_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'primary' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Lied', array(
             'local' => 'lied_id',
             'foreign' => 'id'));

        $this->hasMany('Liedtext as Strophen', array(
             'local' => 'id',
             'foreign' => 'refrain_id'));
    }
}