<?php

/**
 * FkLiederbuchLiedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FkLiederbuchLiedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FkLiederbuchLiedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FkLiederbuchLied');
    }
}