<?php

/**
 * Liedtext
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    adonai
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Liedtext extends BaseLiedtext
{
	public function getShowArray()
	{
		return array(
				'id' => $this->getId(),
				'songId' => $this->getLiedId(),
				'verse' => $this->getStrophe(),
				'refrainId' => $this->getRefrainId(),
				'refrain' => $this->getRefrain()->getRefrain(),
				'rank' => $this->getReihenfolge()
		);
	}

}