<?php

/**
 * LiedtextTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LiedtextTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LiedtextTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Liedtext');
    }
}