<?php

/**
 * LiederbuchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LiederbuchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LiederbuchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Liederbuch');
    }
    
    /**
     * Returns the default liederbuch (the first one)
     */
    public function getDefaultLiederbuch(){
    	$q = $this->createQuery('a')
    		->where('a.id = (SELECT min(id) FROM liederbuch)')
    		->execute();
	    
	    return $q->get(0);
    }
}