<?php

/**
 * LiedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LiedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LiedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lied');
    }
    
    /**
     * Returns an instance of Lied
     * @param unknown_type $bookNr
     * @param unknown_type $liederbuchId
     */
    public function getLied($bookNr, $liederbuchId){
    	$q = $this->createQuery("l")
	      ->innerJoin("l.FkLiederbuchLied fk")
	      ->where("LOWER(fk.liednr) = LOWER(?)", $bookNr)
	      ->andWhere("fk.liederbuch_id = ?", $liederbuchId)
	      ->execute();
	    
	    return $q->get(0);
    }
}