<?php

/**
 * RefrainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RefrainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RefrainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Refrain');
    }
}