<?php

/**
 * Refrain
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    adonai
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Refrain extends BaseRefrain
{
	public function getShowArray()
	{
		return array(
				'id' => $this->getId(),
				'refrainnr' => $this->getRefrainNr(),
				'refrain' => $this->getRefrain(),
				'songId' => $this->getLiedId()
		);
	}
}