<?php

/**
 * RubrikTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RubrikTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RubrikTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rubrik');
    }
}