<?php

/**
 * Rubrik
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    adonai
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Rubrik extends BaseRubrik
{
	/*public function __toString(){
		return $this->getRubrik();
	}*/
	
	public function getOverviewArray()
	{
		return array(
			'id' => $this->getId(),
			'category' => $this->getRubrik(),
			'order' => $this->getReihenfolge()
		);
	}
}